Repository Bearer/bearer, pull requests merged in 2022-12, with the labels that each got.

#271 fix: Temp file path on Linux is missing separator
  pkg/commands/artifact/run.go
Labels: bug, echoes/effort: XS, echoes/intent: bug-fix

#275 chore: Add a wrapper script for running the tests
  scripts/run_tests.sh
Labels: echoes/effort: S, echoes/intent: throughput, echoes/initiative: curio

#273 chore: fix typo for devise and improve test coverage
  integration/flags/.snapshots/TestInitCommand
  pkg/commands/process/settings/custom_detector.yml
  pkg/detectors/custom/.snapshots/TestRubyPasswordLengthClassMinMax
  pkg/detectors/custom/.snapshots/TestRubyPasswordLengthIteration
  pkg/detectors/custom/testdata/config/ruby_password_length.yml
  pkg/detectors/custom/testdata/ruby/password_length/class_min_max/users.rb
  pkg/detectors/custom/testdata/ruby/password_length/iteration/devise.rb
  pkg/detectors/custom/testdata/ruby/password_length/iteration/users.rb
Labels: echoes/intent: bug-fix

#276 feat: harden integration tests
  integration/flags/init_test.go
  integration/internal/testhelper/testhelper.go
Labels: echoes/initiative: curio

#295 fix: Password reported by application-level encryption policy
  integration/flags/.snapshots/TestInitCommand
  integration/policies/.snapshots/TestPolicies-application_level_encryption_missing_schema_rb
  integration/policies/.snapshots/TestPolicies-application_level_encryption_missing_structure_sql
  pkg/commands/process/settings/policies/application_level_encryption.rego
Labels: echoes/effort: XS, echoes/intent: bug-fix, echoes/initiative: curio

#298 feat: add static compilation flag to release
  goreleaser/darwin.yaml
  goreleaser/linux.yaml
Labels: bug, echoes/effort: M, echoes/initiative: curio

#304 fix: Improve policy placeholder for empty scan results
  pkg/report/output/stats/stats.go
Labels: echoes/effort: S, echoes/intent: bug-fix, echoes/initiative: curio

#305 feat: AMA-3307-fix-scan-usage-showing-on-error-vjeran
  cmd/curio/main.go
  integration/flags/.snapshots/TestReportFlagsShouldFail-invalid-context-flag
  integration/flags/.snapshots/TestReportFlagsShouldFail-invalid-format-flag
  integration/flags/.snapshots/TestReportFlagsShouldFail-invalid-report-flag
  integration/flags/report_flags_test.go
  integration/internal/testhelper/testhelper.go
  pkg/commands/artifact/run.go
  pkg/commands/scan.go
  pkg/flag/options.go
  pkg/flag/report_flags.go
  pkg/flag/scan_flags.go
Labels: echoes/effort: M, echoes/initiative: curio

#309 feat: Do not visit Git-ignored files
  go.mod
  go.sum
  pkg/commands/process/balancer/filelist/filelist.go
  pkg/util/gitutil/gitutil.go
Labels: echoes/effort: M, echoes/intent: bug-fix, echoes/initiative: curio

#307 docs: update datatype generation to handle parents
  docs/_data/datatypes.js
  pkg/classification/db/category_grouping.json
Labels: documentation

#302 feat: Use encrypted_ column prefix to mark SQL detections encrypted
  integration/flags/.snapshots/TestReportFlags-report-dataflow-db-encrypted
  integration/flags/report_flags_test.go
  integration/flags/testdata/db_encrypted/structure.sql
  pkg/commands/process/settings/processors/db_encrypted.rego
  pkg/commands/process/settings/settings.go
  pkg/report/output/dataflow/datatypes/get_extras.go
Labels: echoes/effort: L, echoes/initiative: curio
