Repository Bearer/bearer, pull requests merged in 2023-02, with the labels that each got.

#391 chore: Run Ruby-only policies scan as part of battle testing
  .github/workflows/battle_tests.yml
  battle_tests/Dockerfile
  battle_tests/battle_tests.go
  battle_tests/build/build.go
  battle_tests/db/db.go
  battle_tests/local/local_scan.go
  battle_tests/metrics_scan/metrics_scan.go
  battle_tests/scan/scan.go
  battle_tests/sheet/sheet.go
  battle_tests/sync/sync.go
  go.mod
  go.sum
Labels: CI

#481 fix(docs): add remediation message for newrelic
  pkg/commands/process/settings/rules/ruby/third_parties/new_relic.yml
Labels: documentation, rule

#485 ci: remove duplicates in ruby battle test
  battle_tests/db/github/ruby.json
Labels: CI

#486 feat(rules): add exception rule in ruby
  integration/rules/rules_test.go
  pkg/commands/process/settings/rules/ruby/lang/exception.yml
  pkg/commands/process/settings/rules/ruby/lang/exception/.snapshots/TestRubyLangExceptionDataflow-dataflow_ruby_lang_exception_datatype_leak.rb
  pkg/commands/process/settings/rules/ruby/lang/exception/.snapshots/TestRubyLangExceptionDataflow-dataflow_ruby_lang_exception_ok_no_datatypes.rb
  pkg/commands/process/settings/rules/ruby/lang/exception/.snapshots/TestRubyLangExceptionSummary-summary_ruby_lang_exception_datatype_leak.rb
  pkg/commands/process/settings/rules/ruby/lang/exception/.snapshots/TestRubyLangExceptionSummary-summary_ruby_lang_exception_ok_no_datatypes.rb
  pkg/commands/process/settings/rules/ruby/lang/exception/testdata/datatype_leak.rb
  pkg/commands/process/settings/rules/ruby/lang/exception/testdata/ok_no_datatypes.rb
Labels: documentation

#456 docs: add github action doc
  docs/_data/nav.js
  docs/docs.md
  docs/guides/github-action.md
  docs/guides/guides.json
Labels: documentation

#505 docs(fix): change terminology on support page
  docs/reference/supported-languages.md
Labels: documentation

#490 docs: rule UX improvements
  docs/.gitignore
  docs/_data/github.js
  docs/_data/rules.js
  docs/_src/_includes/breadcrumbs.njk
  docs/_src/_includes/layouts/doc.njk
  docs/_src/_includes/nav.njk
  docs/_src/styles/tailwind.css
  docs/contributing/contributing.json
  docs/explanations/discovery-and-classification.md
  docs/explanations/explanations.json
  docs/explanations/index.md
  docs/explanations/reports.md
  docs/package-lock.json
  docs/package.json
  docs/reference/index.md
  docs/reference/reference.json
  docs/reference/rule-pages.njk
  docs/reference/rules.njk
Labels: documentation

#523 docs(feat): add 404 page
  docs/404.md
  docs/_data/meta.js
Labels: documentation

#571 docs(fix): resolve incomplete sitemap bug
  docs/11tydata.json
  docs/reference/rule-pages.njk
Labels: documentation

#608 docs: remove incorrect SCA acronym from discovery page
  docs/explanations/discovery-and-classification.md
Labels: documentation

#601 docs: add CWE and OWASP data to rule pages
  docs/.eleventy.js
  docs/_data/cweList.json
  docs/_data/owaspURLs.json
  docs/reference/rule-pages.njk
  docs/reference/rules.njk
Labels: documentation

#610 ci(goreleaser): update deprecated argument
  .github/workflows/canary.yml
  .github/workflows/release.yml
Labels: CI

#633 ci: only push canary to dockerhub
  .github/workflows/canary.yml
  .goreleaser/canary.yaml
Labels: bug, CI

#663 docs(update): Updating documentation
  docs/_data/nav.js
  docs/docs.md
  docs/explanations/reports.md
  docs/guides/custom-rule.md
  docs/quickstart.md
  docs/reference/index.md
  docs/reference/installation.md
  docs/reference/rules.njk
  docs/reference/supported-languages.md
Labels: documentation

#620 docs(rename): readme updates
  README.md
  docs/assets/img/bearer-logo-dark.svg
  docs/assets/img/bearer-logo-light.svg
Labels: documentation

#665 docs: Update Video in Readme
  README.md
Labels: documentation

#666 docs: FIx favicon & install instruction
  docs/assets/img/curio-logo-dark.svg
  docs/assets/img/curio-logo-light.svg
  docs/assets/img/favicon.ico
  docs/assets/img/favicon.svg
  docs/reference/installation.md
Labels: documentation

#681 docs(fix): readme broken link
  README.md
Labels: documentation
