Repository Bearer/bearer, pull requests merged in 2023-01, with the labels that each got.

#325 feat: Extend Ruby file custom detector to cover IO.open
  integration/custom_detectors/.snapshots/TestCustomDetectors-ruby_file_detection
  integration/custom_detectors/testdata/ruby/ruby_file_detection.rb
  integration/flags/.snapshots/TestInitCommand
  pkg/commands/process/settings/custom_detector.yml
Labels: enhancement, echoes/effort: S, echoes/initiative: curio

#322 feat: add dirs for loading custom detectors and policies
  integration/flags/.snapshots/TestExternalPolicies-test_external_policies
  integration/flags/.snapshots/TestInitCommand
  integration/flags/.snapshots/TestMetadataFlags-help-scan
  integration/flags/.snapshots/TestMetadataFlags-scan-help
  integration/flags/.snapshots/TestReportFlagsShouldFail-invalid-context-flag
  integration/flags/.snapshots/TestReportFlagsShouldFail-invalid-format-flag
  integration/flags/.snapshots/TestReportFlagsShouldFail-invalid-report-flag
  integration/flags/external_policies_test.go
  integration/flags/init_test.go
  integration/flags/metadata_flags_test.go
  integration/flags/report_flags_test.go
  integration/flags/report_output_flags_test.go
  integration/flags/testdata/external_policies/detectors/detect_users_export.yml
  integration/flags/testdata/external_policies/policies/policies/common.rego
  integration/flags/testdata/external_policies/policies/policies/leakage.rego
  integration/flags/testdata/external_policies/policies/users_export.yml
  integration/flags/testdata/external_policies/scan_data/detect_ruby_logger.rb
  integration/internal/testhelper/testhelper.go
  pkg/commands/artifact/run.go
  pkg/commands/init.go
  pkg/commands/process/settings/custom_detector.yml
  pkg/commands/process/settings/custom_detectors/detect_encrypted_ruby_class_properties.yml
  pkg/commands/process/settings/custom_detectors/detect_rails_cookies.yml
  pkg/commands/process/settings/custom_detectors/detect_rails_insecure_communication.yml
  pkg/commands/process/settings/custom_detectors/detect_rails_insecure_ftp.yml
  pkg/commands/process/settings/custom_detectors/detect_rails_insecure_ftp_data.yml
  pkg/commands/process/settings/custom_detectors/detect_rails_insecure_smtp.yml
  pkg/commands/process/settings/custom_detectors/detect_rails_jwt.yml
  pkg/commands/process/settings/custom_detectors/detect_rails_session.yml
  pkg/commands/process/settings/custom_detectors/detect_ruby_logger.yml
  pkg/commands/process/settings/custom_detectors/detect_ruby_third_party_data_send.yml
  pkg/commands/process/settings/custom_detectors/detect_ruby_weak_encryption.yml
  pkg/commands/process/settings/custom_detectors/detect_sql_create_public_table.yml
  pkg/commands/process/settings/custom_detectors/encrypt_method_call.yml
  pkg/commands/process/settings/custom_detectors/initialize_ruby_blowfish_encryption.yml
  pkg/commands/process/settings/custom_detectors/initialize_ruby_openssl_pkey_dsa_encryption.yml
  pkg/commands/process/settings/custom_detectors/initialize_ruby_openssl_pkey_rsa_encryption.yml
  pkg/commands/process/settings/custom_detectors/initialize_ruby_rc4_encryption.yml
  pkg/commands/process/settings/custom_detectors/ruby_blowfish_method_call.yml
  pkg/commands/process/settings/custom_detectors/ruby_file_detection.yml
  pkg/commands/process/settings/custom_detectors/ruby_http_get_detection.yml
  pkg/commands/process/settings/custom_detectors/ruby_http_get_insecure.yml
  pkg/commands/process/settings/custom_detectors/ruby_http_post_detection.yml
  pkg/commands/process/settings/custom_detectors/ruby_http_post_insecure.yml
  pkg/commands/process/settings/custom_detectors/ruby_openssl_pkey_method_call.yml
  pkg/commands/process/settings/custom_detectors/ruby_openssl_pkey_rsa_method_call.yml
  pkg/commands/process/settings/custom_detectors/ruby_password_length.yml
  pkg/commands/process/settings/custom_detectors/ssl_certificate_verification_disabled.yml
  pkg/commands/process/settings/load_external_detectors.go
  pkg/commands/process/settings/load_external_policies.go
  pkg/commands/process/settings/settings.go
  pkg/commands/scan.go
  pkg/flag/detector_flags.go
  pkg/flag/options.go
  pkg/flag/policy_flags.go
  pkg/flag/scan_flags.go
Labels: enhancement, echoes/effort: XL, echoes/initiative: curio

#331 test: Add integration test for Ruby/Rails JWT policy
  integration/policies/.snapshots/TestPolicies-ruby_jwt_leaking
  integration/policies/policies_test.go
  integration/policies/testdata/ruby/jwt_leaking.rb
Labels: echoes/initiative: curio

#348 fix: Only reuse cached detections if the cached run completed
  pkg/commands/artifact/run.go
Labels: echoes/intent: bug-fix, echoes/initiative: curio

#376 feat: add curio ascii logo using ansi escape codes
  integration/flags/.snapshots/TestMetadataFlags-help
  pkg/commands/app.go
Labels: UX

#338 feat: Support installation via the most common Linux package managers
  .github/workflows/release.yml
  .goreleaser.yaml
  README.md
Labels: CI

#390 ci: add missing login for ghcr
  .github/workflows/canary.yml
  .github/workflows/release.yml
Labels: bug, CI

#392 ci: add missing env for ghcr
  .github/workflows/canary.yml
  .github/workflows/release.yml
Labels: bug, CI

#394 ci: add docker login
  .github/workflows/canary.yml
  .github/workflows/release.yml
Labels: bug, CI

#461 feat: test framework for new detectors
  new/detector/composition/composition.go
  new/detector/composition/ruby/.snapshots/TestRuby-object.rb
  new/detector/composition/ruby/ruby.go
  new/detector/composition/ruby/ruby_test.go
  new/detector/composition/ruby/testdata/rule.yml
  new/detector/composition/ruby/testdata/testcases/object.rb
  new/detector/composition/testhelper/testhelper.go
  new/detector/implementation/generic/datatype/datatype.go
  new/detector/implementation/generic/insecureurl/insecureurl.go
  new/detector/implementation/generic/types/types.go
  new/detector/implementation/ruby/object/object.go
  new/detector/implementation/ruby/object/properties.go
  new/detector/implementation/ruby/property/property.go
  new/detector/implementation/ruby/string/string.go
  new/detector/types/types.go
  new/scanner/scanner.go
  pkg/detectors/javascript/datatype/datatype.go
Labels: enhancement

#462 docs: explain use of env files in contrubution guidelines
  docs/contributing/code.md
Labels: documentation
